# Basic Information
title: Khawaja Ghulam Alamdar
position: Researcher
affiliation: Laboratory for Robotics and Intelligent Control Systems (LARICS)
email: khawaja.alamdar11@gmail.com

# Search Engine Optimization (SEO)
keywords: robotics, multi-robot systems, multi-agent systems, autonomous systems, mobile robotics
description: This is the homepage of Khawaja G. Alamdar
canonical: https://khalamdar11.github.io/

# Links
google_scholar: https://scholar.google.com/citations?user=zwRA42cAAAAJ&hl=en
cv_link: assets/files/CV_imrcl_15Aug.pdf
github_link: https://github.com/KhAlamdar11
linkedin: https://www.linkedin.com/in/khalamdar/

# Images
avatar: ./assets/img/khawaja.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - _includes/publications.md
  - _includes/projects.md
